version: "3"
services:
  pokemon-app:
    image: pokemon-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app:ro
    environment:
      NODE_ENV: development
      DB_HOST: db # Use the service name of the database container
      DB_USER: name
      DB_PASSWORD: 1234
      DB_DATABASE: pokemon_db
      DB_PORT: 5432

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: name
      POSTGRES_DB: pokemon_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Define the volume
volumes:
  data:
